### ISSUE TITLE
Support for usability score and rule groups

### ISSUE THREAD

**Issue by jrcryer** [addyosmani/psi#44]
The API supports scores for both speed and usability (https://developers.google.com/speed/docs/insights/v2/first-app#background).  Questions:

* Should we integrate this into the output of PSI?  
* Should we allow the definition of two thresholds?  If single threshold is defined, do we ignore usability score? Or should we apply the same threshold to both?
* Should we continue to support a single threshold value?

Thoughts? @addyosmani @sindresorhus @PaulKinlan

**Comment by PaulKinlan** [comment]
I am not sure the second score is in the API yet. There was a beta version
a while ago but I can't recall it being pushed public.... I'll check with
the eng team.

**Comment by PaulKinlan** [comment]
Looking at the docs it is :) let me double check but yes we should :)

**Comment by jrcryer** [comment]
Thanks @PaulKinlan - I'll try to get this in over the next week

**Comment by addyosmani** [comment]
Usability scores and rule groups should now be in.
