### ISSUE TITLE
Include link to OR option to fetch optimised resources

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/psi#53]
The PageSpeed Insights service can now output optimised resources based on the same strategy options supported for reporting (mobile, desktop). 

If we wanted, we could output a link to download resources as part of the report or some sort of `--download` flag for fetching the output of the optimisation routine.

Mobile:
```
https://developers.google.com/speed/pagespeed/insights/optimizeContents?url=YOUR_URL_HERE&strategy=mobile
```

Desktop:

```
https://developers.google.com/speed/pagespeed/insights/optimizeContents?url=YOUR_URL_HERE&strategy=desktop
```

**Comment by hemanth** [comment]
This can be closed now :)
