### ISSUE TITLE
Install not working for me.

### ISSUE THREAD

**Issue by theskillwithin** [addyosmani/psi#55]
I am probably doing something wrong here.  Please advice:

➜  austinpeterson git:(master) ✗ sudo npm install --save psi
Password:
npm WARN deprecated jws@0.0.2: Security update: Versions below 3.0.0 are deprecated.
psi@1.0.6 node_modules/psi
├── prepend-http@1.0.1
├── object-assign@2.1.1
├── pretty-bytes@1.0.4 (get-stdin@4.0.1)
├── sort-on@1.2.0 (dot-prop@2.1.0)
├── meow@3.1.0 (indent-string@1.2.1, minimist@1.1.1, camelcase-keys@1.0.0)
├── repeating@1.1.3 (is-finite@1.0.1)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── humanize-url@1.0.1 (strip-url-auth@1.0.0, normalize-url@1.2.1)
├── lodash@3.9.3
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, configstore@0.3.2, latest-version@1.0.0)
└── googleapis@1.1.5 (string-template@0.2.1, async@0.9.2, request@2.51.0, gapitoken@0.1.4)
➜  austinpeterson git:(master) ✗ psi
zsh: command not found: psi
➜  austinpeterson git:(master) ✗

**Comment by daryl** [comment]
You're missing the global flat on your install command:

    sudo npm install psi -g

**Comment by theskillwithin** [comment]
➜  SCBA  sudo npm install psi -g
npm WARN deprecated jws@0.0.2: Security update: Versions below 3.0.0 are deprecated.
/usr/local/bin/psi -> /usr/local/lib/node_modules/psi/cli.js
psi@1.0.6 /usr/local/lib/node_modules/psi
├── prepend-http@1.0.1
├── object-assign@2.1.1
├── pretty-bytes@1.0.4 (get-stdin@4.0.1)
├── sort-on@1.2.0 (dot-prop@2.1.0)
├── repeating@1.1.3 (is-finite@1.0.1)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── meow@3.1.0 (indent-string@1.2.1, minimist@1.1.1, camelcase-keys@1.0.0)
├── humanize-url@1.0.1 (strip-url-auth@1.0.0, normalize-url@1.2.1)
├── lodash@3.9.3
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, configstore@0.3.2, latest-version@1.0.0)
└── googleapis@1.1.5 (string-template@0.2.1, async@0.9.2, request@2.51.0, gapitoken@0.1.4)
➜  SCBA

**Comment by callumlocke** [comment]
@theskillwithin unless I'm missing something, it looks like that installed correctly. There's a warning about a deprecated module, but no errors, so the `psi` command should work now. Are you still having problems?
