### ISSUE TITLE
Add promise API option?

### ISSUE THREAD

**Issue by callumlocke** [addyosmani/psi#56]
Would you consider an optional promise API (in addition to the Node callback-style API)?

For example:

```js
var psi = require('psi');

// get the PageSpeed Insights report
psi('html5rocks.com', function (err, data) {
  console.log(data.score);
  console.log(data.pageStats);
});

// OR: same thing, but promise-style
psi('html5rocks.com').then(function (data) {
  console.log(data.score);
  console.log(data.pageStats);
});


// output a formatted report to the terminal
psi.output('html5rocks.com', function (err) {
  console.log('done');
});

// OR promise-style
psi.output('html5rocks.com').then(function () {
  console.log('done');
});
```

(I want this mainly for easy interoperability with other Promise-driven code, so I don't have to manually promisify it first.)

Happy to PR if you agree.

**Comment by nickcolley** [comment]
Could you try something like: https://www.npmjs.com/package/es6-promisify

**Comment by callumlocke** [comment]
@nickcolley see my comment above. I think this should be a built in feature.

**Comment by sindresorhus** [comment]
:+1: Should be switched to promise only (no point in both) and use [pinkie-promise](https://github.com/floatdrop/pinkie-promise) as polyfill.

PR welcome if @addyosmani agrees.

**Comment by addyosmani** [comment]
PR welcome. Would personally love to see us switching to promises for this.
