### ISSUE TITLE
psi CLI always reports "connect ETIMEDOUT"

### ISSUE THREAD

**Issue by YDSS** [addyosmani/psi#58]
I'm in China and my network is fine(I tested it both in company and my home).And I tried both `Chinese website` and `google.com`, it always takes a long time with nothing and then reports **"connect ETIMEDOUT"** in terminal. But I can use `PageSpeed Insights`, the website page to analyse my website. I need help~

<img width="1280" alt="1437181384" src="https://cloud.githubusercontent.com/assets/6086537/8759645/d4a398d2-2d2b-11e5-83c0-be58eec190df.png">

**Comment by addyosmani** [comment]
We haven't been able to reproduce this but it may well be region specific. I'll see if we can repro the issues you're seeing once we've wrapped up our current work on the next release.

**Comment by YDSS** [comment]
That'll be great, thanks!
