### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by Xaviju** [addyosmani/psi#64]
This link in Readme is broken
```
Run mobile and desktop performance tests for your deployed site using **Google PageSpeed Insights** V2 with tidy reporting for your build process.
```
Links to: https://developers.google.com/speed/docs/insights/v2/getting_started

**Comment by addyosmani** [comment]
It looks like the URL was updated to https://developers.google.com/speed/docs/insights/v2/getting-started. We should update it for sure.
