### ISSUE TITLE
psi doesn't return anything for a localhost url

### ISSUE THREAD

**Issue by daedlock** [addyosmani/psi#68]
When I try to run psi on a `localhost`, I get an empty response. I even tried adding a host to my hosts file and made it point to localhost, still getting nothing.  
![1 deadlock hossams-macbook-pro zsh 2016-01-07 16-04-27](https://cloud.githubusercontent.com/assets/842346/12172229/56ad5976-b558-11e5-8316-d72653e78f3f.png)

**Comment by dvLden** [comment]
As I can read, it works only when uploaded to public. Local testing does not work :octocat: :sob:

**Comment by buren** [comment]
You can use something like https://ngrok.com/ which is recommended in the [README](https://github.com/addyosmani/psi#getting-psi-into-your-build-process).

**Comment by DylanPiercey** [comment]
Why not build in ngrok? I don't think you need an api key or anything with the node client.

**Comment by buren** [comment]
Hm, why build it in? `ngrok` is super simple to install and when installed its just a matter of running `ngrok http 9000` if you want to publicly expose port 9000. Any way it would of course be up to @addyosmani :)

**Comment by ptkach** [comment]
It uses pagespeedonline from google api under the hood, that's why it knows nothing about your localhost web site.

**Comment by daedlock** [comment]
Thanks all, seems like `ngrok` is the way to make this work at the meantime!
