### ISSUE TITLE
basic auth support

### ISSUE THREAD

**Issue by MobiusHorizons** [addyosmani/psi#76]
We are trying to run psi against a site that hasn't been released yet. The platform we are on requires us to have basic http authentication on the site before it is released. I would expect psi to work with url's of the type `http(s)?://username:password@domain.tld`. This fails for our site, despite working in browsers and even `curl`.

**Comment by MobiusHorizons** [comment]
After digging into the code to determine if I could provide a pull request, I have determined that the url is being passed correctly to the `googleapis` package, and it is a fault of either the Page speed Insights API or the `googleapis` package.

**Comment by davidhellmann** [comment]
@MobiusHorizons do you solve this problem otherwise?

**Comment by MobiusHorizons** [comment]
No, we were unable to run against that instance. We simply had to run it against a different instance with slightly lower performance, that is primarily meant for testing. Basic auth support would still be very much appreciated, but I understand that that is a question for the google api, not this package.

**Comment by davidhellmann** [comment]
All right, thanks u! My fellow had an Idea to switch the auth file for the PSI task and do that again after it's done to protect the site. 

- site protected
- change file
- site open
- run psi
- change file
- site protected 

but we found no time until now to test it. We use buddy.works as deployment tool. Maybe an interesting approach for you. 

Cheers!
