### ISSUE TITLE
 why i use `psi todomvc.com --strategy=mobile` to make a problem？

### ISSUE THREAD

**Issue by Kelier** [addyosmani/psi#86]
Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25)

**Comment by DanielRuf** [comment]
This is a TLS issue as the website does not support https.

**Comment by sindresorhus** [comment]
Yup, not related to PSI. I've changed the URL we use in the examples.
