### ISSUE TITLE
Gulp-util deprecation warning

### ISSUE THREAD

**Issue by Zweihander-Main** [addyosmani/psi#87]
[gulp-util has been deprecated](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) and now throws a warning when installing psi:
`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`

The dependency tree that results in this warning is:
``` 
psi@3.1.0
  -- download@4.4.3
    -- gulp-decompress@1.2.0
      -- gulp-util@3.0.8
````

The package 'download' (in recent versions) no longer uses 'gulp-decompress' and no longer installs 'gulp-util' as a dependency in the tree - see https://github.com/kevva/download/issues/150

I think updating the 'download' dependency to a more recent version should remove the warning and solve the issue though it looks like it might require changing `psi/lib/output.js` since the syntax appears to have changed.

**Comment by DanielRuf** [comment]
Which version of `download` does not rely on this?

**Comment by Zweihander-Main** [comment]
Looks like `download` version 5.0.0 and up would fix this as that's when `gulp-decompress` was removed.

https://github.com/kevva/download/commit/49d6bcbbfb2c784397b72ab7bda820079aeebf15#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 is the relevant diff.

**Comment by sindresorhus** [comment]
The `download` dependency has been updated.
