### ISSUE TITLE
Outdated download dependency has a security vulnerability

### ISSUE THREAD

**Issue by anselmbradford** [addyosmani/psi#91]
There's a [security vulnerability](https://snyk.io/vuln/npm:tunnel-agent:20170305) in the version of `download` that this project uses because of the dependent `tunnel-agent`:
![screen shot 2018-06-27 at 3 08 28 pm](https://user-images.githubusercontent.com/704760/41994293-f8dadc3e-7a1b-11e8-9a42-27cba8195c48.png)

Outdated `download` noted [here](https://github.com/addyosmani/psi/issues/87#issuecomment-381448470) too.

**Comment by sindresorhus** [comment]
The `download` dependency has been updated.
