### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by anselmbradford** [addyosmani/psi#93]
Repo maintainers are not responding to security vulnerability [PRs](https://github.com/addyosmani/psi/pulls). Is this project abandoned?

**Comment by DanielRuf** [comment]
This is one of the reasons why such big repos (# of stars) should be under an org account.

**Comment by MarcusJT** [comment]
Plus it's described as "Run mobile and desktop performance tests for your deployed site using Google PageSpeed Insights V2 with tidy reporting for your build process." but the API is now on v5 and v2 was deprecated/decommissioned long ago.

It's still referenced in Google's "Web Fundamentals" guidance so I've raised an issue about it at https://github.com/google/WebFundamentals/issues/7269

**Comment by sindresorhus** [comment]
It was just updated to PageSpeed v4. There's an effort to update it to v5: #97

**Comment by sindresorhus** [comment]
> This is one of the reasons why such big repos (# of stars) should be under an org account.

I don't see how that would help. It would still require people to maintain it.

**Comment by DanielRuf** [comment]
Sure but it would be easier to build teams and add real maintainers with the needed rights.

**Comment by sindresorhus** [comment]
Adding maintainers is not the obstacle. @addyosmani is happy to add new maintainers. The difficulty is to find maintainers.

**Comment by addyosmani** [comment]
Hey folks. I have to apologize for the delayed response here. Sindre is correct. 

We've been focused on trying to align Chrome's speed tooling projects (Lighthouse, Chrome User Experience Report, PageSpeed Insights) and I wanted to wait until PSI V5 was finally out before looking at a refresh of this module. 

Thanks to some kind work from the community, a V5 revision is now being explored. I would welcome any and all feedback or help with maintenance once we have that new version in a testable place. Given that the PSI report now contains so much additional information, input on how this is presented will be useful.
